apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: caterer
  name: caterer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: caterer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: caterer
    spec:
      containers:
      - env:
        - name: KAFKA_HOST
          value: kafka-service
        - name: SPRING_DATA_MONGODB_HOST
          value: mongodb
        image: alimjd/caterer-service-image
        imagePullPolicy: ""
        name: caterer
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
